name: Frontend CI

on:
  push:
    branches: [ main ]

jobs:
  abc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout
      - name: Install Node
        uses: actions/setup-node
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build project
        run: npm run build